[gdf_workshop]

name = "gdf_workshop"

version = "0.0.1"

requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["gdf_workshop"] 
exclude = ["data"] 

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"